version: '3'
services:
  app:
    container_name: app
    build: ./docker
    volumes: 
      - .:/var/www
    depends_on: 
      - db

  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=database
      - MYSQL_USER=db-user
      - MYSQL_PASSWORD=db-pass
      - TZ='Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  mysql-data:
    driver: local